name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync --locked --extra dev

      - name: Pytest
        run: uv run pytest

      - name: Mypy
        run: uv run mypy src/it2ui tests

      - name: Ruff format (check)
        run: uv run ruff format --check src/it2ui tests

      - name: Ruff lint
        run: uv run ruff check src/it2ui tests
